// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {app} from '../models';
import {context} from '../models';

export function CancelTask():Promise<dto.BasicResult>;

export function ExportReport(arg1:string):Promise<dto.ExportResult>;

export function GetCompletedJobs():Promise<app.CompletedJobResult>;

export function GetOutputDir():Promise<string>;

export function GetPreview(arg1:number):Promise<app.PreviewResult>;

export function GetTaskStatus():Promise<dto.TaskStatusResult>;

export function OpenOutputDir():Promise<dto.BasicResult>;

export function PauseTask():Promise<dto.BasicResult>;

export function ResumeTask():Promise<dto.BasicResult>;

export function ScanInputPaths(arg1:Array<string>):Promise<dto.ScanResult>;

export function SelectInputDir():Promise<dto.SelectDirResult>;

export function SelectInputPaths():Promise<dto.SelectPathsResult>;

export function SelectOutputDir():Promise<dto.SelectDirResult>;

export function StartCompress(arg1:string,arg2:string,arg3:string,arg4:number):Promise<dto.BasicResult>;

export function Startup(arg1:context.Context):Promise<void>;
