// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTask() {
  return window['go']['app']['App']['CancelTask']();
}

export function ExportReport(arg1) {
  return window['go']['app']['App']['ExportReport'](arg1);
}

export function GetCompletedJobs() {
  return window['go']['app']['App']['GetCompletedJobs']();
}

export function GetOutputDir() {
  return window['go']['app']['App']['GetOutputDir']();
}

export function GetPreview(arg1) {
  return window['go']['app']['App']['GetPreview'](arg1);
}

export function GetTaskStatus() {
  return window['go']['app']['App']['GetTaskStatus']();
}

export function OpenOutputDir() {
  return window['go']['app']['App']['OpenOutputDir']();
}

export function PauseTask() {
  return window['go']['app']['App']['PauseTask']();
}

export function ResumeTask() {
  return window['go']['app']['App']['ResumeTask']();
}

export function ScanInputPaths(arg1) {
  return window['go']['app']['App']['ScanInputPaths'](arg1);
}

export function SelectInputDir() {
  return window['go']['app']['App']['SelectInputDir']();
}

export function SelectInputPaths() {
  return window['go']['app']['App']['SelectInputPaths']();
}

export function SelectOutputDir() {
  return window['go']['app']['App']['SelectOutputDir']();
}

export function StartCompress(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['StartCompress'](arg1, arg2, arg3, arg4);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}
